---
name: Checks

on: [push]

jobs:
    test-lint: # Id of job
        name: Test and Lint # Display name
        runs-on: ubuntu-20.04
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout # Make the code available
              uses: actions/checkout@v2
            # "docker-compose" is now replaced with "docker compose" (without hyphen) for this ubuntu image in Github Actions
            - name: Test
              run: docker compose run --rm app sh -c "python manage.py test"
            - name: Lint
              run: docker compose run --rm app sh -c "flake8"
